const DURATION_OF_SHORTS = 40;
const SCREEN_SIZE = { BIG: 1280, MIDDLE: 768 };
const CARDS_FOR = { BIG_SCREEN: 12, MIDDLE_SCREEN: 8, MOBILE: 5 };
const MORE_CARDS = { MANY: 3, FEW: 2 };

export { DURATION_OF_SHORTS, SCREEN_SIZE, CARDS_FOR, MORE_CARDS };