export const SAVE_MOVIE = 'SAVE_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const SET_SAVED_MOVIES = 'SET_SAVED_MOVIES';
export const SET_MAIN_MOVIES = 'SET_MAIN_MOVIES';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';

export const CHANGE_TOGGLE_STATE = 'CHANGE_TOGGLE_STATE';

export const SET_NUMBER_OF_CARDS = 'SET_NUMBER_OF_CARDS';
export const SET_CARDS_IN_ROW = 'SET_CARDS_IN_ROW';

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_RESPONSE_MESSAGE = 'RESPONSE_MESSAGE';
export const CLEAR_RESPONSE_MESSAGE = "CLEAR_RESPONSE_MESSAGE";